// Function: ctor_285
// Address: 0x4f9da0
//
int ctor_285()
{
  int v0; // eax
  int v1; // eax

  qword_4FC1740 = (__int64)&unk_49EED30;
  v0 = _InterlockedExchangeAdd64((volatile signed __int64 *)&unk_4FA0230, 1u);
  word_4FC174C &= 0xF000u;
  qword_4FC1788 = (__int64)qword_4FA01C0;
  qword_4FC1750 = 0;
  qword_4FC1758 = 0;
  qword_4FC1760 = 0;
  dword_4FC1748 = v0;
  qword_4FC1798 = (__int64)&unk_4FC17B8;
  qword_4FC17A0 = (__int64)&unk_4FC17B8;
  qword_4FC1768 = 0;
  qword_4FC1770 = 0;
  qword_4FC17E8 = (__int64)&unk_49E74E8;
  word_4FC17F0 = 256;
  qword_4FC1778 = 0;
  qword_4FC1780 = 0;
  qword_4FC1740 = (__int64)&unk_49EEC70;
  qword_4FC1790 = 0;
  byte_4FC17D8 = 0;
  qword_4FC17F8 = (__int64)&unk_49EEDB0;
  qword_4FC17A8 = 4;
  dword_4FC17B0 = 0;
  byte_4FC17E0 = 0;
  sub_16B8280(&qword_4FC1740, "enable-memcpy-dag-opt", 21);
  word_4FC17F0 = 257;
  byte_4FC17E0 = 1;
  qword_4FC1770 = 56;
  LOBYTE(word_4FC174C) = word_4FC174C & 0x9F | 0x20;
  qword_4FC1768 = (__int64)"Gang up loads and stores generated by inlining of memcpy";
  sub_16B88A0(&qword_4FC1740);
  __cxa_atexit(sub_12EDEC0, &qword_4FC1740, &qword_4A427C0);
  qword_4FC1660 = (__int64)&unk_49EED30;
  v1 = _InterlockedExchangeAdd64((volatile signed __int64 *)&unk_4FA0230, 1u);
  word_4FC166C &= 0xF000u;
  qword_4FC1670 = 0;
  qword_4FC1678 = 0;
  qword_4FC1680 = 0;
  qword_4FC1688 = 0;
  qword_4FC1690 = 0;
  dword_4FC1668 = v1;
  qword_4FC16B8 = (__int64)&unk_4FC16D8;
  qword_4FC16C0 = (__int64)&unk_4FC16D8;
  qword_4FC16A8 = (__int64)qword_4FA01C0;
  qword_4FC1698 = 0;
  qword_4FC1708 = (__int64)&unk_49E74C8;
  qword_4FC16A0 = 0;
  qword_4FC16B0 = 0;
  qword_4FC1660 = (__int64)&unk_49EEB70;
  qword_4FC16C8 = 4;
  dword_4FC16D0 = 0;
  qword_4FC1718 = (__int64)&unk_49EEDF0;
  byte_4FC16F8 = 0;
  dword_4FC1700 = 0;
  byte_4FC1714 = 1;
  dword_4FC1710 = 0;
  sub_16B8280(&qword_4FC1660, "ldstmemcpy-glue-max", 19);
  qword_4FC1690 = 40;
  qword_4FC1688 = (__int64)"Number limit for gluing ld/st of memcpy.";
  dword_4FC1700 = 0;
  byte_4FC1714 = 1;
  dword_4FC1710 = 0;
  LOBYTE(word_4FC166C) = word_4FC166C & 0x9F | 0x20;
  sub_16B88A0(&qword_4FC1660);
  return __cxa_atexit(sub_12EDEA0, &qword_4FC1660, &qword_4A427C0);
}
