// Function: ctor_656
// Address: 0x59b730
//
int __fastcall ctor_656(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  int v4; // edx
  __int64 v5; // r12
  __int64 v6; // rax
  unsigned __int64 v7; // rdx
  __int64 v8; // rdx
  __int64 v9; // rcx
  int v10; // edx
  __int64 v11; // r12
  __int64 v12; // rax
  unsigned __int64 v13; // rdx
  __int64 v14; // rdx
  __int64 v15; // rcx
  int v16; // edx
  __int64 v17; // rbx
  __int64 v18; // rax
  unsigned __int64 v19; // rdx

  qword_5039600 = (__int64)&unk_49DC150;
  v4 = _InterlockedExchangeAdd64((volatile signed __int64 *)sub_C523C0(a1, a2, a3, a4), 1u);
  qword_5039650 = 0x100000000LL;
  dword_503960C &= 0x8000u;
  word_5039610 = 0;
  qword_5039618 = 0;
  qword_5039620 = 0;
  dword_5039608 = v4;
  qword_5039628 = 0;
  qword_5039630 = 0;
  qword_5039638 = 0;
  qword_5039640 = 0;
  qword_5039648 = (__int64)&unk_5039658;
  qword_5039660 = 0;
  qword_5039668 = (__int64)&unk_5039680;
  qword_5039670 = 1;
  dword_5039678 = 0;
  byte_503967C = 1;
  v5 = sub_C57470();
  v6 = (unsigned int)qword_5039650;
  v7 = (unsigned int)qword_5039650 + 1LL;
  if ( v7 > HIDWORD(qword_5039650) )
  {
    sub_C8D5F0((char *)&unk_5039658 - 16, &unk_5039658, v7, 8);
    v6 = (unsigned int)qword_5039650;
  }
  *(_QWORD *)(qword_5039648 + 8 * v6) = v5;
  LODWORD(qword_5039650) = qword_5039650 + 1;
  qword_5039688 = 0;
  qword_5039690 = (__int64)&unk_49D9748;
  qword_5039698 = 0;
  qword_5039600 = (__int64)&unk_49DC090;
  qword_50396A0 = (__int64)&unk_49DC1D0;
  qword_50396C0 = (__int64)nullsub_23;
  qword_50396B8 = (__int64)sub_984030;
  sub_C53080(&qword_5039600, "enable-memcpy-dag-opt", 21);
  LOWORD(qword_5039698) = 257;
  LOBYTE(qword_5039688) = 1;
  qword_5039630 = 56;
  LOBYTE(dword_503960C) = dword_503960C & 0x9F | 0x20;
  qword_5039628 = (__int64)"Gang up loads and stores generated by inlining of memcpy";
  sub_C53130(&qword_5039600);
  __cxa_atexit(sub_984900, &qword_5039600, &qword_4A427C0);
  qword_5039520 = (__int64)&unk_49DC150;
  v10 = _InterlockedExchangeAdd64((volatile signed __int64 *)sub_C523C0(sub_984900, &qword_5039600, v8, v9), 1u);
  qword_5039570 = 0x100000000LL;
  word_5039530 = 0;
  dword_503952C &= 0x8000u;
  qword_5039538 = 0;
  qword_5039540 = 0;
  dword_5039528 = v10;
  qword_5039548 = 0;
  qword_5039550 = 0;
  qword_5039558 = 0;
  qword_5039560 = 0;
  qword_5039568 = (__int64)&unk_5039578;
  qword_5039580 = 0;
  qword_5039588 = (__int64)&unk_50395A0;
  qword_5039590 = 1;
  dword_5039598 = 0;
  byte_503959C = 1;
  v11 = sub_C57470();
  v12 = (unsigned int)qword_5039570;
  v13 = (unsigned int)qword_5039570 + 1LL;
  if ( v13 > HIDWORD(qword_5039570) )
  {
    sub_C8D5F0((char *)&unk_5039578 - 16, &unk_5039578, v13, 8);
    v12 = (unsigned int)qword_5039570;
  }
  *(_QWORD *)(qword_5039568 + 8 * v12) = v11;
  LODWORD(qword_5039570) = qword_5039570 + 1;
  qword_50395A8 = 0;
  qword_50395B0 = (__int64)&unk_49DA090;
  qword_50395B8 = 0;
  qword_5039520 = (__int64)&unk_49DBF90;
  qword_50395C0 = (__int64)&unk_49DC230;
  qword_50395E0 = (__int64)nullsub_58;
  qword_50395D8 = (__int64)sub_B2B5F0;
  sub_C53080(&qword_5039520, "ldstmemcpy-glue-max", 19);
  qword_5039550 = 40;
  qword_5039548 = (__int64)"Number limit for gluing ld/st of memcpy.";
  LODWORD(qword_50395A8) = 0;
  BYTE4(qword_50395B8) = 1;
  LODWORD(qword_50395B8) = 0;
  LOBYTE(dword_503952C) = dword_503952C & 0x9F | 0x20;
  sub_C53130(&qword_5039520);
  __cxa_atexit(sub_B2B680, &qword_5039520, &qword_4A427C0);
  qword_5039440 = (__int64)&unk_49DC150;
  v16 = _InterlockedExchangeAdd64((volatile signed __int64 *)sub_C523C0(sub_B2B680, &qword_5039520, v14, v15), 1u);
  dword_503944C &= 0x8000u;
  word_5039450 = 0;
  qword_5039490 = 0x100000000LL;
  qword_5039458 = 0;
  qword_5039460 = 0;
  qword_5039468 = 0;
  dword_5039448 = v16;
  qword_5039470 = 0;
  qword_5039478 = 0;
  qword_5039480 = 0;
  qword_5039488 = (__int64)&unk_5039498;
  qword_50394A0 = 0;
  qword_50394A8 = (__int64)&unk_50394C0;
  qword_50394B0 = 1;
  dword_50394B8 = 0;
  byte_50394BC = 1;
  v17 = sub_C57470();
  v18 = (unsigned int)qword_5039490;
  v19 = (unsigned int)qword_5039490 + 1LL;
  if ( v19 > HIDWORD(qword_5039490) )
  {
    sub_C8D5F0((char *)&unk_5039498 - 16, &unk_5039498, v19, 8);
    v18 = (unsigned int)qword_5039490;
  }
  *(_QWORD *)(qword_5039488 + 8 * v18) = v17;
  LODWORD(qword_5039490) = qword_5039490 + 1;
  qword_50394C8 = 0;
  qword_50394D0 = (__int64)&unk_49D9728;
  qword_50394D8 = 0;
  qword_5039440 = (__int64)&unk_49DBF10;
  qword_50394E0 = (__int64)&unk_49DC290;
  qword_5039500 = (__int64)nullsub_24;
  qword_50394F8 = (__int64)sub_984050;
  sub_C53080(&qword_5039440, "has-predecessor-max-steps", 25);
  LODWORD(qword_50394C8) = 0x2000;
  BYTE4(qword_50394D8) = 1;
  LODWORD(qword_50394D8) = 0x2000;
  qword_5039470 = 75;
  LOBYTE(dword_503944C) = dword_503944C & 0x9F | 0x20;
  qword_5039468 = (__int64)"DAG combiner limit number of steps when searching DAG for predecessor nodes";
  sub_C53130(&qword_5039440);
  return __cxa_atexit(sub_984970, &qword_5039440, &qword_4A427C0);
}
